import { motion } from "framer-motion";
import { useEffect, useState } from "react";

const LoveGallery = () => {
    const [images, setImages] = useState<string[]>([]);

    useEffect(() => {
        // This assumes the python script ran and populated the folder.
        // In a real production app we'd have an API, but for this static setup 
        // we can either list known files or try to load them.
        // Since we don't have a backend to list files, and vite import.meta.glob is available:

        // Using simple array for now based on the file names we saw. 
        // In a sophisticated setup we might use a JSON manifest generated by the python script.
        // For now, let's try to load the webp versions of standard files we saw.

        const imageFiles = [
            "IMG_20241215_215532_352.webp",
            "IMG_20241220_152842.webp",
            "IMG_20250103_165355.webp",
            "IMG_20250124_120103.webp",
            "IMG_20250124_120339.webp",
            "IMG_20250202_160151.webp",
            "IMG_20250227_140706.webp",
            "IMG_20250712_123519.webp",
            "IMG_20250719_185706.webp",
            "IMG_20250801_191104.webp",
            "IMG_20250815_125716.webp",
            "IMG_20260130_114113.webp",
            "IMG_4945.webp",
            "IMG_5077.webp",
            "Screenshot_2024-12-01-19-16-28-48_1c337646f29875672b5a61192b9010f9.webp"
        ];
        setImages(imageFiles);

    }, []);

    return (
        <div className="min-h-screen p-4 sm:p-8 bg-gradient-to-br from-pink-50 via-white to-purple-50">
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-8 text-center"
            >
                <h1 className="mb-2 text-3xl font-bold font-serif text-gray-800">Our Beautiful Memories</h1>
                <p className="text-pink-500 font-medium">Every moment with you is a treasure ❤️</p>
            </motion.div>

            <div className="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4 mx-auto max-w-7xl">
                {images.map((img, index) => (
                    <motion.div
                        key={img}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="break-inside-avoid relative group rounded-xl overflow-hidden shadow-lg hover:shadow-xl transition-shadow duration-300"
                    >
                        <img
                            src={`/memories/${img}`}
                            alt="Memory"
                            className="w-full h-auto transform transition-transform duration-500 group-hover:scale-110"
                            loading="lazy"
                            onError={(e) => {
                                // Hide broken images if any
                                (e.target as HTMLImageElement).style.display = 'none';
                            }}
                        />
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300" />
                    </motion.div>
                ))}
            </div>

            <div className="mt-12 text-center text-gray-400 text-sm">
                <p>Made with ❤️ just for you</p>
            </div>
        </div>
    );
};

export default LoveGallery;
